import logging

from crewai import Crew, Process

from src.config.llm import get_llm
from src.crew.agents import create_explainer_agent, create_researcher_agent
from src.crew.tasks import get_explanation_task, get_research_task

logger = logging.getLogger(__name__)


def build_medical_crew(query: str, llm=None) -> Crew:
    """
    Build sequential CrewAI crew with Agent 1 (Researcher) and Agent 2 (Explainer).
    """
    if llm is None:
        llm = get_llm()

    researcher = create_researcher_agent(llm)
    explainer = create_explainer_agent(llm)

    research_task = get_research_task(researcher, query)
    explanation_task = get_explanation_task(explainer, query, research_task)

    return Crew(
        agents=[researcher, explainer],
        tasks=[research_task, explanation_task],
        process=Process.sequential,
        verbose=True,
    )


def run_medical_crew(query: str, llm=None) -> str:
    """
    Execute the medical crew workflow for a query.
    Returns the final Markdown report generated by Agent 2.
    """
    logger.info(f"Kickstarting Medical Crew for query: '{query}'")
    crew = build_medical_crew(query, llm=llm)
    result = crew.kickoff(inputs={"query": query})
    return str(result)
